import { Gift, GiftType, HostProfile, UserProfile, Family, Agency } from "./types";

export const DEFAULT_USER: UserProfile = {
  username: "Pardais_User",
  uniqueId: "pardais_1001",
  avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&h=150&q=80",
  coverPhoto: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80",
  bio: "Senior Live Party Creator on Pardais Party! 🌟",
  gender: "Male",
  country: "Pakistan",
  language: "Urdu / Hinglish",
  coins: 1000000,
  diamonds: 0,
  vipLevel: 0,
  userLevel: 1,
  hostLevel: 1,
  wealthLevel: 1,
  xp: 0,
  familyId: "",
  agencyId: "",
  isVerified: false,
  isBanned: false,
  twoFactorEnabled: false,
  fullName: "",
  dob: "",
  phoneNumber: "",
  kycStatus: "none",
  followersCount: 0,
  followingCount: 0,
  totalLikesCount: 0
};

export const MOCK_GIFTS: Gift[] = [
  { id: "g-rose", name: "Red Rose", cost: 10, type: GiftType.TWO_D, icon: "🌹", color: "from-pink-500 to-rose-600", animationClass: "animate-bounce" },
  { id: "g-heart", name: "Love Heart", cost: 99, type: GiftType.TWO_D, icon: "💖", color: "from-red-500 to-pink-500", animationClass: "animate-pulse" },
  { id: "g-crown", name: "VIP Crown", cost: 999, type: GiftType.THREE_D, icon: "👑", color: "from-yellow-400 to-amber-600", animationClass: "animate-spin" },
  { id: "g-car", name: "Sports Car", cost: 4999, type: GiftType.LUXURY, icon: "🏎️", color: "from-blue-500 to-indigo-600", animationClass: "animate-bounce" },
  { id: "g-rocket", name: "Space Rocket", cost: 9999, type: GiftType.LUXURY, icon: "🚀", color: "from-purple-600 to-pink-600", animationClass: "animate-pulse" },
  { id: "g-dragon", name: "Golden Dragon", cost: 29999, type: GiftType.LUXURY, icon: "🐉", color: "from-amber-500 to-red-600", animationClass: "animate-bounce" }
];

export const MOCK_HOSTS: HostProfile[] = [
  {
    id: "h-ayesha_vip",
    name: "Ayesha_Queen 🔥",
    hostUsername: "ayesha_vip",
    role: "VIP PK Champion",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&h=300&q=80",
    coHostName: "Captain_Leo ⚔️",
    coHostUsername: "captain_leo",
    coHostAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&h=300&q=80",
    viewers: 1850,
    likes: 94200,
    category: "pk",
    subCategory: "pk",
    isLive: true,
    status: "live",
    statusText: "⚔️ 1v1 PK Match vs @captain_leo 🐉",
    bio: "PK Fighter & Top Ranking Streamer on Pardais Party!",
    agencyId: "agency-1",
    inPk: true,
    pkActive: true,
    pkScoreHost: 28500,
    pkScoreOpponent: 24200,
    isDemoHost: true
  },
  {
    id: "h-sahar_official",
    name: "Sahar_Live 👑",
    hostUsername: "sahar_official",
    role: "Official Star Host",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&h=300&q=80",
    coHostName: "Natasha_Star ✨",
    coHostUsername: "natasha_star",
    coHostAvatar: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=300&h=300&q=80",
    viewers: 2420,
    likes: 125200,
    category: "pk",
    subCategory: "pk",
    isLive: true,
    status: "live",
    statusText: "👑 Mega 1v1 PK Championship vs @natasha_star",
    bio: "Welcome to Sahar Live! Official VIP Host. Spread love and positive energy!",
    agencyId: "agency-1",
    inPk: true,
    pkActive: true,
    pkScoreHost: 45200,
    pkScoreOpponent: 42100,
    isDemoHost: true
  },
  {
    id: "h-ali_pro",
    name: "Ali_Pro ⚡",
    hostUsername: "ali_pro",
    role: "PK Battle Master",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&h=300&q=80",
    coHostName: "Maya_Fighter 🥊",
    coHostUsername: "maya_fighter",
    coHostAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&h=300&q=80",
    viewers: 1240,
    likes: 58900,
    category: "pk",
    subCategory: "pk",
    isLive: true,
    status: "live",
    statusText: "🥊 Non-stop 1v1 PK Challenge vs @maya_fighter",
    bio: "Challenging top hosts live!",
    agencyId: "agency-2",
    inPk: true,
    pkActive: true,
    pkScoreHost: 18900,
    pkScoreOpponent: 21400,
    isDemoHost: true
  },
  {
    id: "h-usman_king",
    name: "Usman_King 🦁",
    hostUsername: "usman_king",
    role: "PK Lion Broadcaster",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=300&h=300&q=80",
    coHostName: "Hamza_Champ 🥊",
    coHostUsername: "hamza_champ",
    coHostAvatar: "https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&w=300&h=300&q=80",
    viewers: 950,
    likes: 38400,
    category: "pk",
    subCategory: "pk",
    isLive: true,
    status: "live",
    statusText: "🦁 Lion vs Tiger 1v1 PK Showdown!",
    bio: "Top ranking PK challenger on Pardais Party!",
    agencyId: "agency-2",
    inPk: true,
    pkActive: true,
    pkScoreHost: 15200,
    pkScoreOpponent: 14800,
    isDemoHost: true
  },
  {
    id: "h-zain_singing",
    name: "Zain_Singer 🎙️",
    hostUsername: "zain_singing",
    role: "Music Host",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&h=300&q=80",
    viewers: 750,
    likes: 31000,
    category: "video",
    isLive: true,
    status: "live",
    statusText: "Live Urdu Ghazal & Acoustic Guitar 🎸",
    bio: "Live music sessions every evening!",
    agencyId: "agency-2",
    isDemoHost: true
  },
  {
    id: "h-zara_star",
    name: "Zara_Star ✨",
    hostUsername: "zara_star",
    role: "Superstar Host",
    avatar: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=300&h=300&q=80",
    viewers: 1150,
    likes: 64500,
    category: "video",
    isLive: true,
    status: "live",
    statusText: "Chai Chat & Fun Games ☕",
    bio: "Daily live chat and fan interactions!",
    agencyId: "agency-1",
    isDemoHost: true
  }
];

export const MOCK_FAMILIES: Family[] = [];

export const MOCK_AGENCIES: Agency[] = [];

export const DAILY_MISSIONS = [
  { id: "m-1", title: "Double tap to send 100 Likes", xpReward: 50, coinsReward: 10, status: "Pending", current: 0, target: 100 },
  { id: "m-2", title: "Send any gift to a live host", xpReward: 100, coinsReward: 50, status: "Pending", current: 0, target: 1 },
  { id: "m-3", title: "Type 3 messages in Live Chat", xpReward: 40, coinsReward: 15, status: "Pending", current: 0, target: 3 },
  { id: "m-4", title: "Explore a premium Audio Room", xpReward: 60, coinsReward: 20, status: "Pending", current: 0, target: 1 },
  { id: "m-5", title: "Share Pardais Party host stream with friends", xpReward: 50, coinsReward: 25, status: "Pending", current: 0, target: 1 }
];

export const STATIC_COMMENTS_POOL = [
  "SubhanAllah bohot pyaari aawaaz hai Sahar! 😍",
  "Guys PK support karo fast!! ⚡⚡",
  "Rose gift bhejo sab log family goal complete karna hai!",
  "Nice bio and stream quality is perfect! 🤩",
  "Aadaab! Kaise hain sab log?",
  "Love from Lahore! Keep rocking Pardais Party! 💕",
  "Is this sound coming clearly? Let me know host.",
  "Zain bhai kya entry maari hai, unbeatable!",
  "Mera double tap check karo, work kar raha hai screen pe."
];
